### ISSUE TITLE
Improvement of file_path_checking

### ISSUE THREAD

**Issue by MathieuDepetris** [OB7-IRD/codama#7]
Dear Oceane, when you will have time could you please change in the message(s) of the function file_path_checking the output message to improve the accuracy of the global message.

For example, I have this kind of message :
2023-08-30 15:35:46 - Failure, invalid "extension" argument.
File extension(s) expected is not identical to the "file_path" argument extension.

And it could be better if we could have this kind instead :
2023-08-30 15:35:46 - Failure, invalid "extension" argument.
File extension expected should be "csv", "sql" or "txt" (extension provides is "xls").

**Comment by MathieuDepetris** [comment]
Dear Oceane, in addition to the previous comment, it could be nice if we update this function by following the same evolution that what we do for the "r_type_checking". 

As an example when you run the function now, you have by default an output message like "2024-06-17 14:47:42 - Process "file_path_checking" ran successfully.". 

Another example, you don't have anything in the function to avoid verification of NULL argument (if you put NULL as default argument) and you have to specify "if (! is.null()) before launch the control (as you could remember we modify this behaviour in the "r_type_checking" function.

In any case, it's not hurry and we can discuss that face to face :)

**Comment by OceaneBouhineauIRD** [comment]
It's done normally
